# docker-compose.yml

version: '3'
services:
   web:
    image: "flask-tutorial"
    volumes:
      - "./:/app"
    ports:
     - "8080:5000"
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
    #command: "/usr/local/bin/flask run --host=0.0.0.0"
